FROM maven:3-eclipse-temurin-21 AS maven
WORKDIR /opt/app
COPY src ./src
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn -f /opt/app/pom.xml package -DskipTests

FROM eclipse-temurin:21-jre AS builder
WORKDIR /opt/app
COPY --from=maven /opt/app/target/simplecode-0.0.1-SNAPSHOT.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:21-jre
WORKDIR /application
COPY --from=builder /opt/app/dependencies/ ./    
COPY --from=builder /opt/app/spring-boot-loader/ ./
COPY --from=builder /opt/app/snapshot-dependencies/ ./
COPY --from=builder /opt/app/application/ ./
ENTRYPOINT ["java","org.springframework.boot.loader.launch.JarLauncher"]
